from typing import Protocol, Any, Awaitable, List

class ITelethonClient(Protocol):
    def connect(self) -> Awaitable[None]: ...
    def disconnect(self) -> Awaitable[None]: ...
    def is_user_authorized(self) -> Awaitable[bool]: ...
    def is_connected(self) -> bool: ...
    def start(self) -> Awaitable[Any]: ...
    def get_dialogs(self, limit: int) -> Awaitable[Any]: ...
    def get_messages(self, entity: Any, limit: int = 20, reply_to: int | None = None, ids: List[int] | None = None, offset_id: int = 0) -> Awaitable[Any]: ...
    def get_entity(self, entity: Any) -> Awaitable[Any]: ...
    def download_profile_photo(self, entity: Any, file: Any = None, download_big: bool = False) -> Awaitable[Any]: ...
    def download_media(self, message: Any, file: Any = None, thumb: Any = None) -> Awaitable[Any]: ...
    def __call__(self, request: Any) -> Awaitable[Any]: ...
    def add_event_handler(self, callback: Any, event: Any): ...
    def send_read_acknowledge(self, entity: Any, message: Any = None, max_id: int | None = None, clear_mentions: bool = True, reply_to: int | None = None) -> Awaitable[Any]: ...